2022-09-08 09:20:27,166 INFO    MainThread:108644 [wandb_setup.py:_flush():76] Configure stats pid to 108644
2022-09-08 09:20:27,166 INFO    MainThread:108644 [wandb_setup.py:_flush():76] Loading settings from C:\Users\12137\.config\wandb\settings
2022-09-08 09:20:27,166 INFO    MainThread:108644 [wandb_setup.py:_flush():76] Loading settings from C:\Users\12137\Desktop\source code\FL_image_classification备份\wandb\settings
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:/Users/12137/Desktop/source code/FL_image_classification备份/main.py'}
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_init.py:_log_setup():461] Logging user logs to C:\Users\12137\Desktop\source code\FL_image_classification备份\wandb\run-20220908_092027-1ek8l9y1\logs\debug.log
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_init.py:_log_setup():462] Logging internal logs to C:\Users\12137\Desktop\source code\FL_image_classification备份\wandb\run-20220908_092027-1ek8l9y1\logs\debug-internal.log
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_init.py:init():495] calling init triggers
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-09-08 09:20:27,167 INFO    MainThread:108644 [wandb_init.py:init():548] starting backend
2022-09-08 09:20:27,168 INFO    MainThread:108644 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-09-08 09:20:27,175 INFO    MainThread:108644 [backend.py:ensure_launched():217] starting backend process...
2022-09-08 09:20:27,276 INFO    MainThread:108644 [backend.py:ensure_launched():222] started backend process with pid: 55792
2022-09-08 09:20:27,277 INFO    MainThread:108644 [wandb_init.py:init():558] backend started and connected
2022-09-08 09:20:27,278 INFO    MainThread:108644 [wandb_init.py:init():634] updated telemetry
2022-09-08 09:20:27,282 INFO    MainThread:108644 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-09-08 09:20:29,142 INFO    MainThread:108644 [wandb_run.py:_on_init():1919] communicating current version
2022-09-08 09:20:29,236 INFO    MainThread:108644 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-09-08 09:20:29,237 INFO    MainThread:108644 [wandb_init.py:init():700] starting run threads in backend
2022-09-08 09:20:33,592 INFO    MainThread:108644 [wandb_run.py:_console_start():1893] atexit reg
2022-09-08 09:20:33,592 INFO    MainThread:108644 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2022-09-08 09:20:33,593 INFO    MainThread:108644 [wandb_run.py:_redirect():1803] Wrapping output streams.
2022-09-08 09:20:33,594 INFO    MainThread:108644 [wandb_run.py:_redirect():1827] Redirects installed.
2022-09-08 09:20:33,594 INFO    MainThread:108644 [wandb_init.py:init():732] run started, returning control to user process
2022-09-08 09:20:47,248 INFO    MainThread:108644 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-09-08 09:20:47,471 INFO    MainThread:108644 [wandb_run.py:_restore():1834] restore
2022-09-08 09:20:47,973 INFO    MainThread:108644 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 603
  total_bytes: 603
}

2022-09-08 09:20:48,197 INFO    MainThread:108644 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 603
  total_bytes: 603
}

2022-09-08 09:20:48,312 INFO    MainThread:108644 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 603
  total_bytes: 10481
}

2022-09-08 09:20:48,421 INFO    MainThread:108644 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 603
  total_bytes: 10481
}

2022-09-08 09:20:48,422 INFO    MainThread:108644 [wandb_run.py:_restore():1834] restore
2022-09-08 09:20:50,091 ERROR   MainThread:108644 [wandb_run.py:_atexit_cleanup():1883] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\wandb_run.py", line 1871, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\wandb_run.py", line 1992, in _on_finish
    self._footer_file_pusher_status_info(
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\wandb_run.py", line 2910, in _footer_file_pusher_status_info
    Run._footer_single_run_file_pusher_status_info(
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\wandb_run.py", line 2962, in _footer_single_run_file_pusher_status_info
    printer.progress_update(line, percent_done)
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\lib\printer.py", line 99, in progress_update
    wandb.termlog(f"{next(self._progress)} {text}", newline=False)
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\errors\term.py", line 40, in termlog
    _log(
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\wandb\errors\term.py", line 96, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\click\utils.py", line 299, in echo
    file.write(out)  # type: ignore
OSError: [Errno 22] Invalid argument
